### ISSUE TITLE
Put on code.dlang.org

### ISSUE THREAD

**Issue by Laeeth** [symmetryinvestments/smimeasym#1]
When ready.  Also maybe try running dpp in preprocess mode to update Deimos bindings.

The tricky bit I found was openssl versions clashing for SIL.  We really ought to update the version we are using but that's a bit of work.

**Comment by schveiguy** [comment]
Came to request another change, but saw this. It is on code.dlang.org, so this can be closed.

**Comment by burner** [comment]
forget to close this https://code.dlang.org/packages/smimeasym
